fix

diff --git a/home/.config/bashrc_functions b/home/.config/bashrc_functions
--- a/home/.config/bashrc_functions
+++ b/home/.config/bashrc_functions
@@ -51,24 +51,26 @@ function fix_invalid_utf8 () {
 function git_remove_submodule() {
 	SUBMODULE_NAME=$(echo "${1}" | sed 's/\/$//'); shift
 
-		if git submodule status "${SUBMODULE_NAME}" >/dev/null 2>&1; then
-			git submodule deinit -f "${SUBMODULE_NAME}"
-				git rm --cached "${SUBMODULE_NAME}"
-				rm -rf .git/modules/${SUBMODULE_NAME}
-	rm -rf ${SUBMODULE_NAME}
-	git config -f .gitmodules --remove-section "submodule.${SUBMODULE_NAME}"
-		else
-			[ $# -gt 0 ] && echo "fatal: Submodule '${SUBMODULE_NAME}' not found" 1>&2
-				exit 1
-				fi
+	if git submodule status "${SUBMODULE_NAME}" >/dev/null 2>&1; then
+		git submodule deinit -f "${SUBMODULE_NAME}"
+		git rm --cached "${SUBMODULE_NAME}"
+		rm -rf .git/modules/${SUBMODULE_NAME}
+		rm -rf ${SUBMODULE_NAME}
+		git config -f .gitmodules --remove-section "submodule.${SUBMODULE_NAME}"
+	else
+		[ $# -gt 0 ] && echo "fatal: Submodule '${SUBMODULE_NAME}' not found" 1>&2
+		exit 1
+	fi
 }
 
 function start-gpg-agent() {
-	if test -f ${HOME}/.gnupg/gpg-agent-info && kill -0 $(head -n 1 ${HOME}/.gnupg/gpg-agent-info | cut -d: -f2) 2>/dev/null ; then
-		eval $(< ${HOME}/.gnupg/gpg-agent-info)
-	else
-		eval $(gpg-agent --daemon --enable-ssh-support --write-env-file ${HOME}/.gnupg/gpg-agent-info)
+	if [[ $(command -v gpg-agent >/dev/null 2>&1) ]]; then
+		if test -f ${HOME}/.gnupg/gpg-agent-info && kill -0 $(head -n 1 ${HOME}/.gnupg/gpg-agent-info | cut -d: -f2) 2>/dev/null ; then
+			eval $(< ${HOME}/.gnupg/gpg-agent-info)
+		else
+			eval $(gpg-agent --daemon --enable-ssh-support --write-env-file ${HOME}/.gnupg/gpg-agent-info)
+		fi
+		export GPG_AGENT_INFO
+		export SSH_AUTH_SOCK
 	fi
-	export GPG_AGENT_INFO
-	export SSH_AUTH_SOCK
 }
